language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
scala:
  - 2.10.4
  - 2.11.2
jdk:
  - openjdk7
env:
  - ARANGODB_DISABLE_AUTHENTIFICATION=false VERSION=2.2
before_script:
  - "./src/test/travis/arangodb.sh"
notifications:
  email:
    - sumito3478@gmail.com
# vim:set ts=2 sw=2 et:
